USE CADASTRO;
CREATE TABLE COMPRADORES (CPF VARCHAR(11), NOME VARCHAR(100), IDADE SMALLINT UNSIGNED, CIDADE VARCHAR(50), COMPRAS INT UNSIGNED);
CREATE TABLE VENDEDORES (REGISTRO VARCHAR(5), NOME VARCHAR(100), CIDADE VARCHAR(50), PERCENTUAL FLOAT, VENDAS INT UNSIGNED);
CREATE TABLE PRODUTOS (PRODUTO VARCHAR(20), MARCA VARCHAR(100), EMBALAGEM VARCHAR(50), TAMANHO VARCHAR(2), SABOR VARCHAR(50), VALOR FLOAT);
CREATE TABLE VENDAS (VENDA VARCHAR(20), VENDEDOR VARCHAR(100), COMPRADOR VARCHAR(100), PRODUTO VARCHAR(20), DATA_VENDA DATE, VALOR FLOAT);