USE CADASTRO;
SELECT DISTINCT CIDADE FROM COMPRADORES UNION SELECT DISTINCT CIDADE FROM VENDEDORES;
SELECT DISTINCT CIDADE FROM COMPRADORES UNION ALL SELECT DISTINCT CIDADE FROM VENDEDORES;
SELECT DISTINCT CIDADE, NOME, 'COMPRADOR' AS TIPO FROM COMPRADORES UNION SELECT DISTINCT CIDADE, NOME, 'VENDEDOR' AS TIPO FROM VENDEDORES;