USE CADASTRO;
SELECT * FROM COMPRADORES WHERE IDADE >= 18 AND IDADE <= 26;
SELECT * FROM COMPRADORES WHERE CIDADE = 'Areado' OR CIDADE = 'Alterosa';
SELECT * FROM COMPRADORES WHERE NOT(CIDADE = 'Areado') AND IDADE = 20;
SELECT * FROM COMPRADORES WHERE NOT(CIDADE = 'Areado' OR IDADE = 20);
SELECT * FROM PRODUTOS WHERE SABOR IN ('Abacate', 'Uva');
SELECT * FROM PRODUTOS WHERE VALOR BETWEEN 42.57 AND 42.59;