USE CADASTRO;
SELECT CPF, NOME, COUNT(*) AS COMPRAS, ROUND(SUM(VALOR), 2) AS VALOR_GASTO 
FROM COMPRADORES INNER JOIN VENDAS ON COMPRADORES.CPF = VENDAS.COMPRADOR 
GROUP BY CPF, NOME;
SELECT CPF, NOME, COMPRAS, VENDA AS VENDAS 
FROM COMPRADORES LEFT JOIN VENDAS ON COMPRADORES.CPF = VENDAS.COMPRADOR 
WHERE VENDA IS NULL;
SELECT CPF, NOME, COMPRAS, VENDA AS VENDAS 
FROM VENDAS RIGHT JOIN COMPRADORES ON VENDAS.COMPRADOR = COMPRADORES.CPF 
WHERE VENDA IS NULL;