USE CADASTRO;
SELECT CONSULTA.EMBALAGEM, CONSULTA.MAIOR_VALOR FROM 
(SELECT EMBALAGEM, MAX(VALOR) AS MAIOR_VALOR FROM PRODUTOS GROUP BY EMBALAGEM) CONSULTA
WHERE CONSULTA.MAIOR_VALOR >= 20 ORDER BY CONSULTA.MAIOR_VALOR DESC;
SELECT CONSULTA.COMPRADOR, CONSULTA.COMPRAS FROM 
(SELECT COMPRADOR, COUNT(*) AS COMPRAS FROM VENDAS GROUP BY COMPRADOR) CONSULTA
WHERE CONSULTA.COMPRAS > 2;