USE CADASTRO;
SELECT NOME, IDADE FROM COMPRADORES WHERE IDADE = 20;
SELECT NOME, IDADE FROM COMPRADORES WHERE IDADE <> 20;
SELECT NOME, IDADE FROM COMPRADORES WHERE IDADE > 20;
SELECT NOME, IDADE FROM COMPRADORES WHERE IDADE < 20;