USE CADASTRO;
SELECT * FROM PRODUTOS ORDER BY VALOR;
SELECT * FROM PRODUTOS ORDER BY VALOR DESC;
SELECT * FROM PRODUTOS ORDER BY MARCA;
SELECT * FROM PRODUTOS ORDER BY MARCA DESC;
SELECT * FROM PRODUTOS ORDER BY MARCA, VALOR DESC;